---
title: "data download test"
output: html_document
date: "2026-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(epidatr)
library(tidyverse)
```


```{r}
data <- read_csv("https://raw.githubusercontent.com/PopHIVE/Ingest/main/data/respnet/standard/data.csv.gz")
ili_data <- read_csv("https://raw.githubusercontent.com/PopHIVE/Ingest/main/data/delphi_ili_fluview/standard/data.csv.gz")


# filtering the data to state and using "total" as the age demographic

fips <- "26" # Michigan

data <- data %>%
  filter(geography == fips , age == "Total")

# Filter ILI data for state
ili_data <- ili_data %>%
  filter(geography == fips)

tail(data)
tail(ili_data)
```

```{r}

# this is the data on ILI
res <- pub_fluview(
  regions = "mi",
  epiweeks = epirange(201901, 202999)
) %>%
  select(epiweek, region, num_ili, num_patients, num_providers, ili, wili)

```

```{r}

#this is covid, flu, rsv 
url <- paste0(
  "https://data.cdc.gov/resource/kvib-3txy.csv",
  "?$where=site=%27Michigan%27%20AND%20week_ending_date%20>=%20%272019-01-01%27",
  "&$limit=50000"
)

resp_net_mi <- read.csv(url) %>%
  filter(
    age_group == "Overall",
    sex == "Overall",
    race_ethnicity == "Overall",
    rate_type == "Observed"
  ) %>%
  select(surveillance_network, season, week_ending_date, mmwr_year,
         mmwr_week, site, weekly_rate) |>
  mutate(
    week_ending_date = as.Date(week_ending_date),
    weekly_rate      = as.numeric(weekly_rate),
    mmwr_year        = as.integer(mmwr_year),
    mmwr_week        = as.integer(mmwr_week)
  )|>
  pivot_wider(
    names_from = surveillance_network,
    values_from = c(weekly_rate)
  ) |>
  arrange(mmwr_year, mmwr_week) 




resp_net_mi <- resp_net_mi |>
  mutate(
    flu_rate = replace_na(resp_net_mi$`FluSurv-NET`,0),
    rsv_rate = replace_na(resp_net_mi$`RSV-NET`,0),
    covid_rate = replace_na(resp_net_mi$`COVID-NET`,0)
  ) |>
  select(-c(`FluSurv-NET`, `RSV-NET`, `COVID-NET`, Combined))


```

